name = "diffy"
version = "0.1.0"
product-name = "Diffy"
identifier = "io.github.seatedro.diffy"
publisher = "seatedro"
out-dir = "dist/packages"
binaries-dir = "target/release"
before-packaging-command = "bash scripts/prepare-macos-icon-assets.sh && cargo build --release"
icons = [
  "assets/packaging/macos/generated/*.icns",
  "assets/packaging/diffy.ico",
  "assets/packaging/png/*.png",
]
resources = [
  "LICENSE",
  "assets/packaging/macos/generated/Assets.car*",
]

[[binaries]]
main = true
path = "diffy"

[macos]
info-plist-path = "assets/packaging/macos/generated/Info.plist"

[windows]
allow-downgrades = false

[linux]
generate-desktop-entry = true

[nsis]
installer-mode = "currentUser"
appdata-paths = ["$LOCALAPPDATA/$PUBLISHER/$PRODUCTNAME"]
