use std::path::PathBuf;

use crate::core::compare::{CompareMode, LayoutMode, RendererKind};
use crate::platform::secrets::AiKeyKind;
use crate::ui::state::{CompareField, FocusTarget, SettingsSection, SidebarTab};
use crate::ui::theme::ThemeMode;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Action {
    Bootstrap,
    OpenRepositoryDialog,
    OpenRepository(PathBuf),
    OpenRepoPicker,
    OpenRefPicker(CompareField),
    OpenCommandPalette,
    ShowWorkingTree,
    OpenGitHubAuthModal,
    CloseOverlay,
    SetLeftRef(String),
    SetRightRef(String),
    SwapRefs,
    SetActiveRefField(CompareField),
    SwapDraftRefs,
    CommitRefPicker,
    CancelRefPicker,
    SetCompareMode(CompareMode),
    CycleCompareMode,
    OpenCompareMenu,
    ApplyComparePreset(String),
    SetLayoutMode(LayoutMode),
    SetRenderer(RendererKind),
    SetFocus(Option<FocusTarget>),
    InsertText(String),
    Backspace,
    BackspaceWord,
    BackspaceLine,
    DeleteForward,
    DeleteForwardWord,
    // Cursor movement
    CursorLeft,
    CursorRight,
    CursorUp,
    CursorDown,
    CursorWordLeft,
    CursorWordRight,
    CursorHome,
    CursorEnd,
    CursorSoftHome,
    CursorSoftEnd,
    // Selection
    SelectLeft,
    SelectRight,
    SelectUp,
    SelectDown,
    SelectWordLeft,
    SelectWordRight,
    SelectHome,
    SelectEnd,
    SelectSoftHome,
    SelectSoftEnd,
    SelectAll,
    // Clipboard
    Copy,
    Cut,
    Paste(String),
    /// Set cursor and anchor to a specific byte offset (from click-to-position).
    SetTextCursor(usize),
    /// Set cursor to a specific byte offset while keeping anchor (drag selection).
    ExtendTextSelection(usize),
    MoveOverlaySelection(i32),
    ConfirmOverlaySelection,
    TabCompletePickerDir,
    SelectOverlayEntry(usize),
    HoverOverlayEntry(Option<usize>),
    StartCompare,
    CancelCompare,
    StageSelectedFile,
    UnstageSelectedFile,
    DiscardSelectedFile,
    StageFile(usize),
    UnstageFile(usize),
    StageAllFiles,
    UnstageAllFiles,
    StageHunk,
    UnstageHunk,
    DiscardHunk,
    StageHunkAt(i16),
    UnstageHunkAt(i16),
    DiscardHunkAt(i16),
    ToggleLineSelection(usize),
    ToggleLineSelectionRange(usize, usize),
    StageSelectedLines,
    UnstageSelectedLines,
    DiscardSelectedLines,
    ClearLineSelection,
    SelectFile(usize),
    SelectFilePath(String),
    SelectNextFile,
    SelectPreviousFile,
    ScrollFileList(i32),
    /// Scroll the file list by a pixel delta.
    ScrollFileListPx(i32),
    /// Set file list scroll to an absolute pixel position.
    ScrollFileListToPx(u32),
    /// Scroll the active overlay list (picker / command palette) by a pixel delta.
    ScrollActiveOverlayListPx(i32),
    ScrollViewportLines(i32),
    /// Scroll the viewport by a pixel delta.
    ScrollViewportPx(i32),
    ScrollViewportPages(i32),
    ScrollViewportTo(u32),
    HoverViewportRow(Option<usize>),
    GoToNextHunk,
    GoToPreviousHunk,
    GoToNextFile,
    GoToPreviousFile,
    FocusViewport,
    HoverFile(Option<usize>),
    StartGitHubDeviceFlow,
    OpenDeviceFlowBrowser,
    OpenAccountMenu,
    CopyText(String),
    SignOutGitHub,
    DismissToast(usize),
    HoverToast(Option<usize>),
    ToggleWrap,
    SetWrapColumn(u32),
    SetSidebarWidthPx(u32),
    IncreaseUiScale,
    DecreaseUiScale,
    SetUiScalePct(u16),
    ToggleThemeMode,
    SetThemeMode(ThemeMode),
    SetThemeName(String),
    SetWheelScrollLines(u8),
    OpenThemePicker,
    OpenSettings,
    CloseSettings,
    CheckForUpdates,
    InstallUpdate,
    SetSettingsSection(SettingsSection),
    ToggleFolder(String),
    ToggleFileViewed(usize),
    SetSidebarFilter(String),
    ClearSidebarFilter,
    ToggleSidebarMode,
    ToggleSidebar,
    SetSidebarTab(SidebarTab),
    SelectSidebarCommit(String),
    ClearSidebarCommit,
    ScrollCommitListPx(i32),
    ExpandAllFolders,
    CollapseAllFolders,
    OpenSearch,
    CloseSearch,
    SearchNext,
    SearchPrevious,
    ShowKeyboardShortcuts,
    ScrollViewportHalfPage(i32),
    SubmitCommit,
    FetchRemote(String),
    FetchAllRemotes,
    PushCurrentBranch {
        force_with_lease: bool,
    },
    PullCurrentBranch,
    EditorClick(i32, i32),
    EditorDrag(i32, i32),
    EditorScrollPx(i32),
    ExpandContextAbove(usize, u32),
    ExpandContextBelow(usize, u32),
    ExpandAllContext,
    SetAiKey {
        kind: AiKeyKind,
        value: String,
    },
    ClearAiKey {
        kind: AiKeyKind,
    },
    SetAiKeyEditing {
        kind: AiKeyKind,
        editing: bool,
    },
    GenerateCommitMessage,
    Noop,
}
